# Generated by Django 6.0 on 2025-12-18 08:50

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import events.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=2000)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited capacity', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Image of the event', max_length=255, null=True, verbose_name='event_image')),
                ('is_closed', models.BooleanField(default=False, help_text='Is the event closed?')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy for the event', null=True)),
                ('identity', models.CharField(blank=True, max_length=2000, unique=True)),
                ('event_code', models.CharField(default=events.utils.generate_event_code, editable=False, max_length=2000, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_events', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
    ]
