# Generated by Django 6.0 on 2026-02-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_created_by_event_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
