# Generated by Django 6.0 on 2026-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
