# Generated by Django 6.0 on 2026-03-03 20:57

from django.db import migrations, models
import json


def convert_cancellation_policy_to_json(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        if (
            event.cancellation_policy is None
            or str(event.cancellation_policy).strip() == ""
        ):
            event.cancellation_policy = None
            event.save(update_fields=["cancellation_policy"])
        else:
            try:
                # Check if it's already valid JSON
                json.loads(event.cancellation_policy)
            except (ValueError, TypeError):
                # If not, convert the plain text into a JSON string
                event.cancellation_policy = json.dumps(event.cancellation_policy)
                event.save(update_fields=["cancellation_policy"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_content"),
    ]

    operations = [
        migrations.RunPython(
            convert_cancellation_policy_to_json, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="event",
            name="cancellation_policy",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
