# Generated by Django 6.0 on 2026-03-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cancellation_policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
