# Generated by Django 6.0 on 2026-03-03 20:59

from django.db import migrations
import json


def convert_cancellation_policy_to_json(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        if event.cancellation_policy:
            try:
                # Check if it's already valid JSON
                json.loads(event.cancellation_policy)
            except (ValueError, TypeError):
                # If not, convert the plain text into a JSON string
                event.cancellation_policy = json.dumps(event.cancellation_policy)
                event.save(update_fields=["cancellation_policy"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_content"),
    ]

    operations = [
        migrations.RunPython(
            convert_cancellation_policy_to_json, reverse_code=migrations.RunPython.noop
        ),
    ]
