# Generated by Django 6.0 on 2026-03-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cancellation_policy',
        ),
    ]
