# Generated by Django 6.0 on 2026-03-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cancellation_policy_and_more'),
        ('events', '0007_migrate_cancellation_policy_to_json'),
    ]

    operations = [
    ]
