# Generated by Django 6.0 on 2026-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refund_policy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
