# Generated by Django 6.0 on 2026-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_refund_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.JSONField(blank=True, help_text='Long description of the event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='refund_policy',
            field=models.JSONField(blank=True, help_text='Refund policy of the event', null=True),
        ),
    ]
