# Generated by Django 6.1 on 2026-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_content_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='Music & Concerts', help_text='Event Category (e.g. Music & Concerts, Festivals, Tech & Business)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_passcode',
            field=models.CharField(blank=True, help_text='PIN for gate staff to scan tickets without login', max_length=12, null=True),
        ),
    ]
