# Generated by Django 6.0 on 2025-12-25 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaBody',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('body', models.JSONField()),
            ],
            options={
                'verbose_name': 'M-Pesa Body',
                'verbose_name_plural': 'M-Pesa Bodies',
                'ordering': ['-created_at'],
            },
        ),
    ]
