# Generated by Django 6.0 on 2026-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
