# Generated by Django 6.0 on 2026-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], default='PERCENTAGE', max_length=20),
        ),
    ]
