# Generated by Django 6.0 on 2026-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0, help_text='Total number of tickets successfully purchased using this coupon'),
        ),
    ]
