# Generated by Django 6.0 on 2026-03-12 06:37

from django.db import migrations
from django.db.models import Sum


def backfill_tickets_sold(apps, schema_editor):
    Coupon = apps.get_model("coupons", "Coupon")
    Booking = apps.get_model("bookings", "Booking")

    for coupon in Coupon.objects.all():
        result = Booking.objects.filter(
            coupon=coupon, payment_status="COMPLETED"
        ).aggregate(total=Sum("quantity"))
        coupon.tickets_sold = result["total"] or 0
        coupon.save()


def reverse_backfill(apps, schema_editor):
    Coupon = apps.get_model("coupons", "Coupon")
    Coupon.objects.all().update(tickets_sold=0)


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0004_coupon_tickets_sold"),
        ("bookings", "0005_booking_coupon"),
    ]

    operations = [
        migrations.RunPython(backfill_tickets_sold, reverse_backfill),
    ]
