# Generated by Django 6.0 on 2026-03-19 17:41

import coupons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_backfill_coupon_tickets_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=coupons.utils.generate_code, max_length=60, unique=True),
        ),
    ]
