# Generated by Django 6.0 on 2025-12-18 16:04

import django.core.validators
import django.db.models.deletion
import tickettypes.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_available', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited tickets or when is_limited is True to use event capacity', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_limited', models.BooleanField(default=False, help_text='Indicates if ticket type is limited; if True and quantity_available is None, uses event capacity')),
                ('ticket_type_code', models.CharField(default=tickettypes.utils.generate_ticket_type_code, editable=False, max_length=255, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['event', '-price'],
            },
        ),
    ]
