# Generated by Django 6.0 on 2026-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickettypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sales_end',
            field=models.DateTimeField(blank=True, help_text='When ticket sales end. Leave blank to sell until event ends.', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sales_start',
            field=models.DateTimeField(blank=True, help_text='When ticket sales begin. Leave blank to start immediately.', null=True),
        ),
    ]
