# Generated by Django 6.0 on 2026-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickettypes', '0002_tickettype_sales_end_tickettype_sales_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this ticket type or stop sales manually.'),
        ),
    ]
