# Generated by Django 6.0 on 2025-12-14 12:41

import cloudinary.models
import company.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the company', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the company', null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Logo of the company', max_length=255, null=True, verbose_name='company_logo')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, help_text='Banner of the company', max_length=255, null=True, verbose_name='company_banner')),
                ('country', models.CharField(blank=True, help_text='Country of the company', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City of the company', max_length=255, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of the company', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the company', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the company', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Website of the company', null=True)),
                ('company_code', models.CharField(default=company.utils.generate_company_code, editable=False, help_text='Unique code for the company', max_length=10, unique=True)),
                ('manager', models.ForeignKey(help_text='The owner and manager of the company', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
