# Generated by Django 6.0 on 2025-12-18 20:57

import company.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(default=company.utils.generate_company_code, editable=False, help_text='Unique code for the company', max_length=100, unique=True),
        ),
    ]
