# Generated by Django 6.0 on 2025-12-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_unique_manager_company_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_manager_company_name',
        ),
    ]
