# Generated by Django 6.0 on 2025-12-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_unique_manager_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Name of the company', max_length=255, unique=True),
        ),
    ]
