# Generated by Django 6.0 on 2025-12-25 10:29

import bookings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default=bookings.utils.generate_booking_code, editable=False, max_length=100, unique=True),
        ),
    ]
