# Generated by Django 6.0 on 2025-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='callback_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
