# Generated by Django 6.0 on 2025-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_callback_url_booking_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
