# Generated by Django 6.0 on 2025-12-25 10:29

import cloudinary.models
import django.db.models.deletion
import tickets.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_booking_booking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ticket_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('ticket_code', models.CharField(default=tickets.utils.generate_ticket_code, editable=False, max_length=100, unique=True)),
                ('qr_code', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tickets_qr_code')),
                ('is_used', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
