# Generated by Django 6.1 on 2026-09-19 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gate_station',
            field=models.CharField(blank=True, default='Main Gate', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TicketScanLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scanned_code', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('VALID', 'Valid Entry'), ('ALREADY_USED', 'Already Used'), ('INVALID_EVENT', 'Invalid Event'), ('NOT_FOUND', 'Ticket Not Found'), ('UNPAID', 'Unpaid Booking')], max_length=50)),
                ('gate_station', models.CharField(default='Main Gate', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_scan_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Scan Log',
                'verbose_name_plural': 'Ticket Scan Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
